/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobanco;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        textoCajero.setVisible(false);

        jSpinner1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Cajero1 = new javax.swing.JButton();
        Cajero2 = new javax.swing.JButton();
        Cajero3 = new javax.swing.JButton();
        Cajero4 = new javax.swing.JButton();
        jButton_Iniciar = new javax.swing.JButton();
        Persona1 = new javax.swing.JLabel();
        Persona2 = new javax.swing.JLabel();
        Persona3 = new javax.swing.JLabel();
        Persona4 = new javax.swing.JLabel();
        Cola1 = new javax.swing.JLabel();
        Cola2 = new javax.swing.JLabel();
        Cola3 = new javax.swing.JLabel();
        Cola4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        C1_Texto = new javax.swing.JLabel();
        C1_Texto1 = new javax.swing.JLabel();
        C1_Texto2 = new javax.swing.JLabel();
        C1_Texto3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registro1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Registro2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Registro3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Registro4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        Registro5 = new javax.swing.JTextPane();
        textoCajero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JButton_Reiniciar = new javax.swing.JButton();

        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosed(evt);
            }
        });
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cajero1.setText("Cajero1");
        Cajero1.setEnabled(false);
        Cajero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cajero1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 97, 68));

        Cajero2.setText("Cajero 2");
        Cajero2.setEnabled(false);
        jPanel1.add(Cajero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 85, 68));

        Cajero3.setText("Cajero 3");
        Cajero3.setEnabled(false);
        jPanel1.add(Cajero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 0, 85, 68));

        Cajero4.setText("Cajero 4");
        Cajero4.setEnabled(false);
        jPanel1.add(Cajero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 0, 85, 68));

        jButton_Iniciar.setText("Abrir Banco");
        jButton_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IniciarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));
        jPanel1.add(Persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 50));
        jPanel1.add(Persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, 50));
        jPanel1.add(Persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, 50));
        jPanel1.add(Persona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 100, 50));

        Cola1.setText("Cola 1");
        Cola1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Cola1PropertyChange(evt);
            }
        });
        jPanel1.add(Cola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 60));

        Cola2.setText("Cola 2");
        jPanel1.add(Cola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, 60));

        Cola3.setText("Cola 3");
        jPanel1.add(Cola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, 60));

        Cola4.setText("Cola 4");
        jPanel1.add(Cola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 100, 60));

        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jTabbedPane1.addTab("Cajeros.", jPanel1);

        C1_Texto.setText("Cajero 1");

        C1_Texto1.setText("Cajero 2");

        C1_Texto2.setText("Cajero 3");

        C1_Texto3.setText("Cajero 4");

        Registro1.setEditable(false);
        jScrollPane1.setViewportView(Registro1);

        Registro2.setEditable(false);
        jScrollPane2.setViewportView(Registro2);

        Registro3.setEditable(false);
        jScrollPane3.setViewportView(Registro3);

        Registro4.setEditable(false);
        jScrollPane4.setViewportView(Registro4);

        Registro5.setEditable(false);
        jScrollPane5.setViewportView(Registro5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(C1_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(C1_Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(C1_Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(C1_Texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C1_Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1_Texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C1_Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1_Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registo", jPanel2);

        jDialog1.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoCajero.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        textoCajero.setText("Cajeros");

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setText("Escoja que modo desea");

        JButton_Reiniciar.setText("Reiniciar");
        JButton_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(textoCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JButton_Reiniciar)
                        .addGap(127, 127, 127)
                        .addComponent(jButton3)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(11, 11, 11)
                .addComponent(textoCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton_Reiniciar)
                    .addComponent(jButton3))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton2.setVisible(false);
        textoCajero.setVisible(true);
        jSpinner1.setVisible(true);
        cont1 = 1;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton1.setVisible(false);
        textoCajero.setVisible(true);
        jSpinner1.setVisible(true);
        cont1 = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (cont1 == 1) {

            int cajero = (int) jSpinner1.getValue();
            if (cajero == 1) {
                Cajero1.setVisible(true);
                Persona1.setVisible(true);

                Cajero2.setVisible(false);
                Cajero3.setVisible(false);
                Cajero4.setVisible(false);
                Persona2.setVisible(false);
                Persona3.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 2) {
                Cajero2.setVisible(true);
                Persona2.setVisible(true);

                Cajero3.setVisible(false);
                Cajero4.setVisible(false);
                Persona3.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 3) {
                Cajero3.setVisible(true);
                Cajero2.setVisible(true);
                Cajero1.setVisible(true);
                Persona3.setVisible(true);
                Persona2.setVisible(true);
                Persona1.setVisible(true);

                Cajero4.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 4) {
                Cajero1.setVisible(true);
                Cajero2.setVisible(true);
                Cajero3.setVisible(true);
                Cajero4.setVisible(true);
                Persona1.setVisible(true);
                Persona2.setVisible(true);
                Persona3.setVisible(true);
                Persona4.setVisible(true);
            }
            Cola2.setVisible(false);
            Cola3.setVisible(false);
            Cola4.setVisible(false);
            jPanel1.setVisible(true);
            jDialog1.setModal(true);
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(this);
            jDialog1.setVisible(true);

        } else {
            Cola1.setVisible(false);
            Cola2.setVisible(false);
            Cola3.setVisible(false);
            Cola4.setVisible(false);
            int cajero = (int) jSpinner1.getValue();

            if (cajero == 1) {
                Cajero1.setVisible(true);
                Persona1.setVisible(true);

                Cajero2.setVisible(false);
                Cajero3.setVisible(false);
                Cajero4.setVisible(false);
                Persona2.setVisible(false);
                Persona3.setVisible(false);
                Persona4.setVisible(false);
                Cola1.setVisible(true);
                Persona1.setVisible(true);

                Cola2.setVisible(false);
                Persona2.setVisible(false);
                Cola3.setVisible(false);
                Persona3.setVisible(false);
                Cola4.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 2) {
                Cajero2.setVisible(true);
                Persona2.setVisible(true);
                Persona1.setVisible(false);
                Cajero3.setVisible(false);
                Cajero4.setVisible(false);
                Persona3.setVisible(false);
                Persona4.setVisible(false);

                Cola1.setVisible(true);
                Persona1.setVisible(true);
                Cola2.setVisible(true);
                Persona2.setVisible(true);

                Cola3.setVisible(false);
                Persona3.setVisible(false);
                Cola4.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 3) {
                Cajero3.setVisible(true);
                Cajero2.setVisible(true);
                Cajero1.setVisible(true);
                Persona3.setVisible(true);
                Persona2.setVisible(true);
                Persona1.setVisible(true);

                Cajero4.setVisible(false);
                Persona4.setVisible(false);
                Cola1.setVisible(true);
                Persona1.setVisible(true);
                Cola2.setVisible(true);
                Persona2.setVisible(true);
                Cola3.setVisible(true);
                Persona3.setVisible(true);

                Cola4.setVisible(false);
                Persona4.setVisible(false);
            }
            if (cajero == 4) {
                Cajero1.setVisible(true);
                Cajero2.setVisible(true);
                Cajero3.setVisible(true);
                Cajero4.setVisible(true);
                Persona1.setVisible(true);
                Persona2.setVisible(true);
                Persona3.setVisible(true);
                Persona4.setVisible(true);

                Cola1.setVisible(true);
                Persona1.setVisible(true);
                Cola2.setVisible(true);
                Persona2.setVisible(true);
                Cola3.setVisible(true);
                Persona3.setVisible(true);
                Cola4.setVisible(true);
                Persona4.setVisible(true);
            }

            jPanel1.setVisible(true);
            jDialog1.setModal(true);
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(this);
            jDialog1.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JButton_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ReiniciarActionPerformed
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        textoCajero.setVisible(false);

        jSpinner1.setVisible(false);

        jSpinner1.setValue(1);


    }//GEN-LAST:event_JButton_ReiniciarActionPerformed

    private void Cajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cajero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cajero1ActionPerformed

    private void jDialog1WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosed
        /*Cajero1.setVisible(true);
        Cajero2.setVisible(true);
        Cajero3.setVisible(true);
        Cajero4.setVisible(true);*/
    }//GEN-LAST:event_jDialog1WindowClosed

    @SuppressWarnings("empty-statement")
    private void jButton_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IniciarActionPerformed
        Cajero c1 = new Cajero();
        Cajero c2 = new Cajero();
        Cajero c3 = new Cajero();
        Cajero c4 = new Cajero();
        Cola c = new Cola();
        Cola co2 = new Cola();
        Cola co3 = new Cola();
        Cola co4 = new Cola();
        Pila p1 = new Pila();
        Pila p2 = new Pila();
        Pila p3 = new Pila();
        Pila p4 = new Pila();
        int x = (int) jSpinner1.getValue();
        if (cont1 == 1) {
            Registro1.setText("");
            Registro2.setText("");
            Registro3.setText("");
            Registro4.setText("");
            cont2 = 0;
            conta2 = 0;
            conta3 = 0;
            conta4 = 0;
            switch (x) {
                case 1: {
                    Random r = new Random();
                    String transacción = "";
                    c1.setVacio(true);
                    for (int i = 0; i < 70; i++) {
                        int y = r.nextInt(3) + 1;
                        if (y == 1) {
                            transacción = "Deposito";
                        }
                        if (y == 2) {
                            transacción = "Retiro";
                        }
                        if (y == 3) {
                            transacción = "Pago";
                        }
                        c.pone(new Persona("Persona " + i, i, transacción));
                    }
                    for (int i = 0; i < 70; i++) {
                        System.out.println(c.listaPersona.get(i).toString());
                    }

                    op1(c1, c, p1);
                    // Cola1.setText(c.listaPersona.get(0).getNombre());
                    break;
                }
                case 2: {
                    Random r = new Random();
                    String transacción = "";
                    c1.setVacio(true);
                    for (int i = 0; i < 70; i++) {
                        int y = r.nextInt(3) + 1;
                        if (y == 1) {
                            transacción = "Deposito";
                        }
                        if (y == 2) {
                            transacción = "Retiro";
                        }
                        if (y == 3) {
                            transacción = "Pago";
                        }

                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    for (int i = 0; i < 70; i++) {

                        System.out.println(c.listaPersona.get(i).toString());
                    }
                    ArrayList<Integer> array = new ArrayList();
                    //int[] array = new int [69];
                    for (int i = 0; i < 69; i++) {
                        if (i < 20) {
                            array.add(3);
                        }
                        if (i >= 20 && i <= 30) {
                            array.add(2);
                        }
                        if (i > 31) {
                            array.add(1);
                        }
                    }

                    int y = 70;
                    while (!c.listaPersona.isEmpty()) {
                        c.quita();
                        if (c1.isVacio() && c2.isVacio()) {
                            try {

                                System.out.println("hola");

                                int z = r.nextInt(array.size());
                                System.out.println(z);
                                //z*1000
                                Thread.sleep(array.get(z) * 1000);
                                array.remove(z);

                            } catch (Exception e) {

                            }
                            int z = r.nextInt(2) + 1;
                            if (z == 1) {
                                c1.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {

                                    System.out.println(c.listaPersona.get(0).getNombre());
                                    c1.setPersona(c.listaPersona.get(0));

                                    p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c1.setP(p1);
                                    System.out.println(p1.listaTransacción.get(cont2));
                                    registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                    Registro1.setText(registroTotal);
                                    cont2++;
                                    c1.setVacio(true);
                                    if (y != 0) {
                                        // nombre1 = c.listaPersona.get(0).getNombre();

                                    }
                                    if (y > 1) {
                                        //nombre2 = c.listaPersona.get(1).getNombre();

                                    }

                                }

                            } else if (z == 2) {

                                c2.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c2.setPersona(c.listaPersona.get(0));
                                    p2.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c2.setP(p2);
                                    System.out.println(p2.listaTransacción.get(cont3));
                                    registroTotal2 += p2.listaTransacción.get(cont3) + "\n";
                                    Registro2.setText(registroTotal2);
                                    cont3++;
                                    c2.setVacio(true);
                                    if (y != 0) {
                                        //  nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 1) {
                                        //nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }

                                }

                            }

                        }
                        y--;
                    }
                    break;
                }
                case 3: {
                    Random r = new Random();
                    String transacción = "";
                    c1.setVacio(true);
                    for (int i = 0; i < 70; i++) {
                        int y = r.nextInt(3) + 1;
                        if (y == 1) {
                            transacción = "Deposito";
                        }
                        if (y == 2) {
                            transacción = "Retiro";
                        }
                        if (y == 3) {
                            transacción = "Pago";
                        }

                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    for (int i = 0; i < 70; i++) {

                        System.out.println(c.listaPersona.get(i).toString());
                    }
                    ArrayList<Integer> array = new ArrayList();
                    //int[] array = new int [69];
                    for (int i = 0; i < 69; i++) {
                        if (i < 20) {
                            array.add(3);
                        }
                        if (i >= 20 && i <= 30) {
                            array.add(2);
                        }
                        if (i > 31) {
                            array.add(1);
                        }
                    }
                    int y = 70;
                    while (!c.listaPersona.isEmpty()) {
                        c.quita();
                        if (c1.isVacio() && c2.isVacio() && c3.isVacio()) {
                            try {

                                System.out.println("hola");

                                int z = r.nextInt(array.size());
                                System.out.println(z);
                                //z*1000
                                Thread.sleep(array.get(z) * 1000);
                                array.remove(z);

                            } catch (Exception e) {

                            }
                            int z = r.nextInt(3) + 1;
                            if (z == 1) {
                                c1.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {

                                    System.out.println(c.listaPersona.get(0).getNombre());
                                    c1.setPersona(c.listaPersona.get(0));

                                    p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c1.setP(p1);
                                    System.out.println(p1.listaTransacción.get(cont2));
                                    registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                    Registro1.setText(registroTotal);
                                    cont2++;
                                    c1.setVacio(true);
                                    if (y != 0) {
                                        //    nombre1 = c.listaPersona.get(0).getNombre();

                                    }
                                    if (y > 1) {
                                        //   nombre2 = c.listaPersona.get(1).getNombre();

                                    }
                                }

                            } else if (z == 2) {

                                c2.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c2.setPersona(c.listaPersona.get(0));
                                    p2.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c2.setP(p2);
                                    System.out.println(p2.listaTransacción.get(cont3));
                                    registroTotal2 += p2.listaTransacción.get(cont3) + "\n";
                                    Registro2.setText(registroTotal2);
                                    cont3++;
                                    c2.setVacio(true);
                                    if (y != 0) {
                                        //   nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 1) {
                                        //   nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    y--;
                                }

                            } else if (z == 3) {

                                c3.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c3.setPersona(c.listaPersona.get(0));
                                    p3.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c3.setP(p3);
                                    System.out.println(p3.listaTransacción.get(cont4));
                                    registroTotal3 += p3.listaTransacción.get(cont4) + "\n";
                                    Registro3.setText(registroTotal3);
                                    cont4++;
                                    c3.setVacio(true);
                                    if (y != 0) {
                                        // nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 0) {
                                        // nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    y--;
                                }

                            }
                        }

                    }
                    break;
                }
                case 4: {
                    Random r = new Random();
                    String transacción = "";
                    c1.setVacio(true);
                    for (int i = 0; i < 70; i++) {
                        int y = r.nextInt(3) + 1;
                        if (y == 1) {
                            transacción = "Deposito";
                        }
                        if (y == 2) {
                            transacción = "Retiro";
                        }
                        if (y == 3) {
                            transacción = "Pago";
                        }

                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    for (int i = 0; i < 70; i++) {

                        System.out.println(c.listaPersona.get(i).toString());
                    }
                    ArrayList<Integer> array = new ArrayList();
                    //int[] array = new int [69];
                    for (int i = 0; i < 69; i++) {
                        if (i < 20) {
                            array.add(3);
                        }
                        if (i >= 20 && i <= 30) {
                            array.add(2);
                        }
                        if (i > 31) {
                            array.add(1);
                        }
                    }
                    int y = 50;
                    while (!c.listaPersona.isEmpty()) {
                        c.quita();
                        if (c1.isVacio() && c2.isVacio() && c3.isVacio()) {
                            try {

                                System.out.println("hola");

                                int z = r.nextInt(array.size());
                                System.out.println(z);
                                //z*1000
                                Thread.sleep(array.get(z) * 1000);
                                array.remove(z);

                            } catch (Exception e) {

                            }
                            int z = r.nextInt(4) + 1;
                            if (z == 1) {
                                c1.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {

                                    System.out.println(c.listaPersona.get(0).getNombre());
                                    c1.setPersona(c.listaPersona.get(0));

                                    p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c1.setP(p1);
                                    System.out.println(p1.listaTransacción.get(cont2));
                                    registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                    Registro1.setText(registroTotal);
                                    cont2++;
                                    c1.setVacio(true);
                                    if (y != 0) {
                                        //   nombre1 = c.listaPersona.get(0).getNombre();

                                    }
                                    if (y > 1) {
                                        // nombre2 = c.listaPersona.get(1).getNombre();

                                    }
                                }

                            } else if (z == 2) {

                                c2.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c2.setPersona(c.listaPersona.get(0));
                                    p2.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c2.setP(p2);
                                    System.out.println(p2.listaTransacción.get(cont3));
                                    registroTotal2 += p2.listaTransacción.get(cont3) + "\n";
                                    Registro2.setText(registroTotal2);
                                    cont3++;
                                    c2.setVacio(true);
                                    if (y != 0) {
                                        nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 1) {
                                        nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                }

                            } else if (z == 3) {

                                c3.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c3.setPersona(c.listaPersona.get(0));
                                    p3.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c3.setP(p3);
                                    System.out.println(p3.listaTransacción.get(cont4));
                                    registroTotal3 += p3.listaTransacción.get(cont4) + "\n";
                                    Registro3.setText(registroTotal3);
                                    cont4++;
                                    c3.setVacio(true);
                                    if (y != 0) {
                                        nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 1) {
                                        nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                }

                            } else if (z == 4) {

                                c4.setVacio(false);
                                if (!c.listaPersona.isEmpty()) {
                                    c4.setPersona(c.listaPersona.get(0));
                                    p4.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c4.setP(p4);
                                    System.out.println(p4.listaTransacción.get(cont5));
                                    registroTotal4 += p4.listaTransacción.get(cont5) + "\n";
                                    Registro4.setText(registroTotal4);
                                    cont5++;
                                    c4.setVacio(true);
                                    if (y != 0) {
                                        nombre1 = c.listaPersona.get(0).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                    if (y > 1) {
                                        nombre2 = c.listaPersona.get(1).getNombre();
                                        System.out.println(c.listaPersona.get(0).getNombre());

                                    }
                                }

                            }
                        }
                        y--;
                    }
                    break;
                }
            }
            p1.listaTransacción.clear();
            p2.listaTransacción.clear();
            p3.listaTransacción.clear();
            p4.listaTransacción.clear();

            c.listaPersona.clear();
            co2.listaPersona.clear();
            co3.listaPersona.clear();
            co4.listaPersona.clear();
        } else {
            Registro1.setText("");
            Registro2.setText("");
            Registro3.setText("");
            Registro4.setText("");
            cont2 = 0;
            conta2 = 0;
            conta3 = 0;
            conta4 = 0;
            int x1 = (int) jSpinner1.getValue();

            if (x1 == 2) {

                Random r = new Random();
                String transacción = "";
                c1.setVacio(true);
                for (int i = 0; i < 50; i++) {
                    int y = r.nextInt(3) + 1;
                    if (y == 1) {
                        transacción = "Deposito";
                    }
                    if (y == 2) {
                        transacción = "Retiro";
                    }
                    if (y == 3) {
                        transacción = "Pago";
                    }
                    if (i % 2 != 0) {
                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    if (i % 2 == 0) {
                        co2.pone(new Persona("Persona " + i, i, transacción));
                    }
                }
                for (int i = 0; i < 50; i++) {
                    if (i < 25) {
                        System.out.println(c.listaPersona.get(i).toString());

                    }
                    if (i >= 25) {
                        System.out.println(co2.listaPersona.get(i - 25).toString());
                    }
                }
                ArrayList<Integer> array = new ArrayList();
                //int[] array = new int [69];
                for (int i = 0; i < 50; i++) {
                    if (i < 20) {
                        array.add(3);
                    }
                    if (i >= 20 && i < 40) {
                        array.add(2);
                    }
                    if (i >= 41) {
                        array.add(2);
                    }
                }
                int y = 49;

                while (0 < y) {
                    int xd = r.nextInt(2) + 1;
                    // System.out.println("Cajero " + xd);

                    // if (y > 2) {
                    //jDialog1.setVisible(true);
                    try {

                        System.out.println("hola");

                        int z = r.nextInt(array.size());
                        System.out.println(z);
                        //z*1000
                        Thread.sleep(array.get(z) * 1000);
                        array.remove(z);

                    } catch (Exception e) {

                    }

                    //}
                    if (!c.listaPersona.isEmpty()) {
                        if (c1.isVacio() && xd == 1) {

                            if (!c.listaPersona.isEmpty()) {

                                registroTotal2 += "<-----------" + "\n";

                                if (!c.listaPersona.isEmpty()) {
                                    c1.setVacio(false);
                                    System.out.println(c.listaPersona.get(0).getNombre());

                                    c1.setPersona(c.listaPersona.get(0));
                                    p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c1.setP(p1);
                                    System.out.println(p1.listaTransacción.get(cont2));
                                    registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                    Registro1.setText(registroTotal);
                                    cont2++;
                                    if (y != 0) {
                                        //nombre1 = c.listaPersona.get(0).getNombre();

                                    }
                                    if (y > 1) {
                                        // nombre2 = c.listaPersona.get(1).getNombre();

                                    }
                                }
                                if (!c.listaPersona.isEmpty()) {
                                    y--;
                                    c.quita();
                                }
                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema 1 ");

                            }
                            /* try {

                            System.out.println("hola");

                            int z = r.nextInt(array.size());
                            System.out.println(z);
                            //z*1000
                            Thread.sleep(array.get(z) * 1000);
                            array.remove(z);

                        } catch (Exception e) {

                        }*/

                            c1.setVacio(true);

                        }
                    }
                    if (!co2.listaPersona.isEmpty()) {
                        if (c2.isVacio() && xd == 2) {
                            c2.setVacio(false);
                            if (!co2.listaPersona.isEmpty()) {

                                registroTotal += "----------->" + "\n";

                                System.out.println(co2.listaPersona.get(0).getNombre());

                                c2.setPersona(co2.listaPersona.get(0));
                                p2.listaTransacción.add(co2.listaPersona.get(0).getNombre() + " Hizo un " + co2.listaPersona.get(0).getTransaccion());
                                c2.setP(p2);
                                System.out.println(p2.listaTransacción.get(conta2));
                                registroTotal2 += p2.listaTransacción.get(conta2) + "\n";
                                Registro2.setText(registroTotal2);
                                conta2++;
                                if (y != 0) {
                                    //nombre1 = co2.listaPersona.get(0).getNombre();

                                }
                                if (y > 1) {
                                    // nombre2 = co2.listaPersona.get(1).getNombre();

                                }
                                if (!co2.listaPersona.isEmpty()) {
                                    y--;
                                    co2.quita();
                                }
                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema 2");
                            }
                            c2.setVacio(true);

                        }
                    }

                }

                cont2 = 0;
                p1.listaTransacción.clear();
                p2.listaTransacción.clear();
                p3.listaTransacción.clear();
                p4.listaTransacción.clear();

                c.listaPersona.clear();
                co2.listaPersona.clear();
                co3.listaPersona.clear();
                co4.listaPersona.clear();
            }
            if (x1 == 3) {
                Random r = new Random();
                String transacción = "";
                c1.setVacio(true);
                for (int i = 0; i < 50; i++) {
                    int y = r.nextInt(3) + 1;
                    if (y == 1) {
                        transacción = "Deposito";
                    }
                    if (y == 2) {
                        transacción = "Retiro";
                    }
                    if (y == 3) {
                        transacción = "Pago";
                    }
                    if (i < 18) {
                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    if (i >= 18 && i <= 37) {
                        co2.pone(new Persona("Persona " + i, i, transacción));
                    }
                    if (i >= 38) {
                        co3.pone(new Persona("Persona " + i, i, transacción));

                    }
                }
                for (int i = 0; i < 50; i++) {
                    if (i < 18) {
                        System.out.println(c.listaPersona.get(i).toString());

                    }
                    if (i >= 18 && i <= 37) {
                        System.out.println(co2.listaPersona.get(i - 18).toString());
                    }
                    if (i >= 38) {
                        System.out.println(co3.listaPersona.get(i - 38).toString());
                    }
                }
                ArrayList<Integer> array = new ArrayList();
                //int[] array = new int [69];
                for (int i = 0; i < 50; i++) {
                    if (i < 20) {
                        array.add(3);
                    }
                    if (i >= 20 && i < 40) {
                        array.add(2);
                    }
                    if (i >= 41) {
                        array.add(2);
                    }
                }
                int y = 49;

                while (0 < y) {
                    int xd = r.nextInt(3) + 1;
                    // System.out.println("Cajero " + xd);
                    if (y > 2) {

                        try {

                            System.out.println("hola");

                            int z = r.nextInt(array.size());
                            System.out.println(z);
                            //z*1000
                            Thread.sleep(array.get(z) * 1000);
                            array.remove(z);

                        } catch (Exception e) {

                        }

                    }

                    if (c1.isVacio() && xd == 1) {

                        if (!c.listaPersona.isEmpty()) {

                            if (!c.listaPersona.isEmpty()) {
                                c1.setVacio(false);
                                System.out.println(c.listaPersona.get(0).getNombre());

                                c1.setPersona(c.listaPersona.get(0));
                                p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                c1.setP(p1);
                                System.out.println(p1.listaTransacción.get(cont2));
                                registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                Registro1.setText(registroTotal);
                                cont2++;
                                if (y != 0) {
                                    //nombre1 = c.listaPersona.get(0).getNombre();

                                }
                                if (y > 1) {
                                    // nombre2 = c.listaPersona.get(1).getNombre();

                                }
                            }
                            if (!c.listaPersona.isEmpty()) {
                                y--;
                                c.quita();
                            }
                        } else {
                            System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                        }
                        /* try {

                            System.out.println("hola");

                            int z = r.nextInt(array.size());
                            System.out.println(z);
                            //z*1000
                            Thread.sleep(array.get(z) * 1000);
                            array.remove(z);

                        } catch (Exception e) {

                        }*/

                        c1.setVacio(true);

                    }

                    if (c2.isVacio() && xd == 2) {
                        c2.setVacio(false);
                        if (!co2.listaPersona.isEmpty()) {

                            System.out.println(co2.listaPersona.get(0).getNombre());

                            c2.setPersona(co2.listaPersona.get(0));
                            p2.listaTransacción.add(co2.listaPersona.get(0).getNombre() + " Hizo un " + co2.listaPersona.get(0).getTransaccion());
                            c2.setP(p2);
                            System.out.println(p2.listaTransacción.get(conta2));
                            registroTotal2 += p2.listaTransacción.get(conta2) + "\n";
                            Registro2.setText(registroTotal2);
                            conta2++;
                            if (y != 0) {
                                //nombre1 = co2.listaPersona.get(0).getNombre();

                            }
                            if (y > 1) {
                                // nombre2 = co2.listaPersona.get(1).getNombre();

                            }
                            if (!co2.listaPersona.isEmpty()) {
                                co2.quita();
                                y--;
                            }
                        } else {
                            System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                        }
                        c2.setVacio(true);

                    }

                    if (c3.isVacio() && xd == 3) {
                        c3.setVacio(false);
                        if (!co3.listaPersona.isEmpty()) {

                            System.out.println(co3.listaPersona.get(0).getNombre());

                            c3.setPersona(co3.listaPersona.get(0));
                            p3.listaTransacción.add(co3.listaPersona.get(0).getNombre() + " Hizo un " + co3.listaPersona.get(0).getTransaccion());
                            c3.setP(p3);
                            System.out.println(p3.listaTransacción.get(conta3));
                            registroTotal3 += p3.listaTransacción.get(conta3) + "\n";
                            Registro3.setText(registroTotal3);
                            conta3++;
                            if (y != 0) {
                                //nombre1 = co2.listaPersona.get(0).getNombre();

                            }
                            if (y > 1) {
                                // nombre2 = co2.listaPersona.get(1).getNombre();

                            }
                            if (!co3.listaPersona.isEmpty()) {
                                co3.quita();
                                y--;
                            }
                        } else {
                            System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                        }
                        c3.setVacio(true);

                    }

                }
                p1.listaTransacción.clear();
                p2.listaTransacción.clear();
                p3.listaTransacción.clear();
                p4.listaTransacción.clear();

                c.listaPersona.clear();
                co2.listaPersona.clear();
                co3.listaPersona.clear();
                co4.listaPersona.clear();

                cont2 = 0;
                conta2 = 0;
                conta3 = 0;
                conta4 = 0;

            }
            if (x1 == 4) {
                Random r = new Random();
                String transacción = "";
                c1.setVacio(true);
                for (int i = 0; i < 48; i++) {
                    int y = r.nextInt(3) + 1;
                    if (y == 1) {
                        transacción = "Deposito";
                    }
                    if (y == 2) {
                        transacción = "Retiro";
                    }
                    if (y == 3) {
                        transacción = "Pago";
                    }

                    if (i <= 12) {
                        c.pone(new Persona("Persona " + i, i, transacción));

                    }
                    if (i >= 13 && i <= 24) {
                        co2.pone(new Persona("Persona " + i, i, transacción));
                    }
                    if (i >= 25 && i <= 36) {
                        co3.pone(new Persona("Persona " + i, i, transacción));
                    }
                    if (i >= 37 && i <= 48) {
                        co4.pone(new Persona("Persona " + i, i, transacción));
                    }

                }
                for (int i = 0; i < 48; i++) {
                    if (i <= 12) {
                        System.out.println(c.listaPersona.get(i).toString());

                    }
                    if (i >= 13 && i <= 24) {
                        System.out.println(co2.listaPersona.get(i - 13).toString());
                    }
                    if (i >= 25 && i <= 36) {
                        System.out.println(co3.listaPersona.get(i - 25).toString());
                    }
                    if (i >= 37 && i <= 48) {
                        System.out.println(co4.listaPersona.get(i - 37).toString());
                    }
                }

                ArrayList<Integer> array = new ArrayList();

                for (int i = 0; i < 48; i++) {
                    if (i < 24) {
                        array.add(3);

                    }
                    if (i >= 24) {
                        array.add(2);
                    }

                }
                int y = 48;

                while (0 < y) {

                    int xd = r.nextInt(4) + 1;

                    // System.out.println("Cajero " + xd);
                    //jDialog1.setVisible(true);
                    try {

                        //System.out.println("hola");

                        int z = r.nextInt(array.size());
                       // System.out.println(z);
                        //z*1000
                        Thread.sleep(array.get(z) * 1000);
                        array.remove(z);

                    } catch (Exception e) {

                    }

                    if (!c.listaPersona.isEmpty()) {

                        if (c1.isVacio() && xd == 1) {

                            valc1 += aux;
                            if (!c.listaPersona.isEmpty()) {

                                if (!c.listaPersona.isEmpty()) {
                                    c1.setVacio(false);
                                    System.out.println(c.listaPersona.get(0).getNombre());

                                    c1.setPersona(c.listaPersona.get(0));
                                    p1.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                                    c1.setP(p1);
                                    System.out.println(p1.listaTransacción.get(cont2));
                                    registroTotal += p1.listaTransacción.get(cont2) + "\n";
                                    Registro1.setText(registroTotal);
                                    cont2++;
                                    if (y != 0) {
                                        //nombre1 = c.listaPersona.get(0).getNombre();

                                    }
                                    if (y > 1) {
                                        // nombre2 = c.listaPersona.get(1).getNombre();

                                    }
                                } else {
                                    System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                                }
                                if (!c.listaPersona.isEmpty()) {
                                    y--;
                                    c.quita();
                                }

                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                            }
                            

                            c1.setVacio(true);

                        }
                    }

                    if (!co2.listaPersona.isEmpty()) {

                        if (c2.isVacio() && xd == 2) {
                            c2.setVacio(false);
                            valc2 += aux;
                            if (!co2.listaPersona.isEmpty()) {

                                System.out.println(co2.listaPersona.get(0).getNombre());

                                c2.setPersona(co2.listaPersona.get(0));
                                p2.listaTransacción.add(co2.listaPersona.get(0).getNombre() + " Hizo un " + co2.listaPersona.get(0).getTransaccion());
                                c2.setP(p2);
                                System.out.println(p2.listaTransacción.get(conta2));
                                registroTotal2 += p2.listaTransacción.get(conta2) + "\n";
                                Registro2.setText(registroTotal2);
                                conta2++;
                                if (y != 0) {
                                    //nombre1 = co2.listaPersona.get(0).getNombre();

                                }
                                if (y > 1) {
                                    // nombre2 = co2.listaPersona.get(1).getNombre();

                                }

                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                            }
                            if (!co2.listaPersona.isEmpty()) {
                                co2.quita();
                                y--;
                            }

                            c2.setVacio(true);

                        }
                    }

                    if (!co3.listaPersona.isEmpty()) {

                        if (c3.isVacio() && xd == 3) {
                            c3.setVacio(false);
                            valc3 += aux;
                            if (!co3.listaPersona.isEmpty()) {

                                System.out.println(co3.listaPersona.get(0).getNombre());

                                c3.setPersona(co3.listaPersona.get(0));
                                p3.listaTransacción.add(co3.listaPersona.get(0).getNombre() + " Hizo un " + co3.listaPersona.get(0).getTransaccion());
                                c3.setP(p3);
                                System.out.println(p3.listaTransacción.get(conta3));
                                registroTotal3 += p3.listaTransacción.get(conta3) + "\n";
                                Registro3.setText(registroTotal3);
                                conta3++;
                                if (y != 0) {
                                    //nombre1 = co2.listaPersona.get(0).getNombre();

                                }
                                if (y > 1) {
                                    // nombre2 = co2.listaPersona.get(1).getNombre();

                                }

                                if (!co3.listaPersona.isEmpty()) {
                                    co3.quita();
                                    y--;
                                }

                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                            }
                            c3.setVacio(true);

                        }
                    }
                    if (!co4.listaPersona.isEmpty()) {
                        if (c4.isVacio() && xd == 4) {

                            c4.setVacio(false);
                            valc4 += aux;
                            if (!co4.listaPersona.isEmpty()) {

                                System.out.println(co4.listaPersona.get(0).getNombre());

                                c4.setPersona(co4.listaPersona.get(0));
                                p4.listaTransacción.add(co4.listaPersona.get(0).getNombre() + " Hizo un " + co4.listaPersona.get(0).getTransaccion());
                                c3.setP(p3);
                                System.out.println(p4.listaTransacción.get(conta4));
                                registroTotal4 += p4.listaTransacción.get(conta4) + "\n";
                                Registro4.setText(registroTotal4);
                                conta4++;
                                if (y != 0) {
                                    //nombre1 = co2.listaPersona.get(0).getNombre();

                                }
                                if (y > 1) {
                                    // nombre2 = co2.listaPersona.get(1).getNombre();

                                }
                                if (!co4.listaPersona.isEmpty()) {
                                    co4.quita();
                                    y--;
                                }

                            } else {
                                System.out.println("Es una oficina Gubernamental, se cayó el sistema");
                            }
                            c4.setVacio(true);

                        }
                    }

                }

                cont2 = 0;
                p1.listaTransacción.clear();
                p2.listaTransacción.clear();
                p3.listaTransacción.clear();
                p4.listaTransacción.clear();

                c.listaPersona.clear();
                co2.listaPersona.clear();
                co3.listaPersona.clear();
                co4.listaPersona.clear();

            }
            String r5 = "";
            r5 += "Tiempo en cajeros:  " + "\n";
            r5 += "Cajero 1: " + valc1 + "\n";
            r5 += "Cajero 2: " + valc2 + "\n";
            r5 += "Cajero 3: " + valc3 + "\n";
            r5 += "Cajero 4: " + valc4 + "\n";
            Registro5.setText(r5);

            System.out.println("quedan: ");
            for (int i = 0; i < co4.listaPersona.size(); i++) {
                System.out.println(co4.listaPersona.toString());
            }

        }
    }//GEN-LAST:event_jButton_IniciarActionPerformed

    private void Cola1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Cola1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Cola1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void op1(Cajero c1, Cola c, Pila p) {
        int t = 0;
        ArrayList<Integer> array = new ArrayList();
        //int[] array = new int [69];
        for (int i = 0; i < 69; i++) {
            if (i < 20) {
                array.add(3);
            }
            if (i >= 20 && i <= 30) {
                array.add(2);
            }
            if (i > 31) {
                array.add(1);
            }
        }

        Hilo x = new Hilo();
        x.start();
        x.setColaPersona(c);
        x.setBarra(jProgressBar1);
        x.setAvanzar(true);
        x.setVive(true);
        int y = 69;

        while (0 < y) {

            // if (y > 2) {
            //jDialog1.setVisible(true);
            //  x.run();
            try {

                System.out.println("hola");
                Random r = new Random();
                int z = r.nextInt(array.size());
                System.out.println(z);
                //z*1000
               // Thread.sleep(array.get(z) * 1000);
                array.remove(z);

            } catch (Exception e) {

            }

            //  }
            if (c1.isVacio()) {

                c.quita();
                if (!c.listaPersona.isEmpty()) {

                    System.out.println(c.listaPersona.get(0).getNombre());

                    c1.setPersona(c.listaPersona.get(0));
                    p.listaTransacción.add(c.listaPersona.get(0).getNombre() + " Hizo un " + c.listaPersona.get(0).getTransaccion());
                    c1.setP(p);
                    System.out.println(p.listaTransacción.get(cont2));
                    registroTotal += p.listaTransacción.get(cont2) + "\n";
                    Registro1.setText(registroTotal);
                    cont2++;
                    if (y != 0) {
                        nombre1 = c.listaPersona.get(0).getNombre();

                    }
                    if (y > 1) {
                        nombre2 = c.listaPersona.get(1).getNombre();

                    }
                }

            }

            y--;
        }
        c1.setVacio(false);
        cont2 = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C1_Texto;
    private javax.swing.JLabel C1_Texto1;
    private javax.swing.JLabel C1_Texto2;
    private javax.swing.JLabel C1_Texto3;
    private javax.swing.JButton Cajero1;
    private javax.swing.JButton Cajero2;
    private javax.swing.JButton Cajero3;
    private javax.swing.JButton Cajero4;
    private javax.swing.JLabel Cola1;
    private javax.swing.JLabel Cola2;
    private javax.swing.JLabel Cola3;
    private javax.swing.JLabel Cola4;
    private javax.swing.JButton JButton_Reiniciar;
    private javax.swing.JLabel Persona1;
    private javax.swing.JLabel Persona2;
    private javax.swing.JLabel Persona3;
    private javax.swing.JLabel Persona4;
    private javax.swing.JTextPane Registro1;
    private javax.swing.JTextPane Registro2;
    private javax.swing.JTextPane Registro3;
    private javax.swing.JTextPane Registro4;
    private javax.swing.JTextPane Registro5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Iniciar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel textoCajero;
    // End of variables declaration//GEN-END:variables
int cont1 = 0;
    String nombre1 = "";
    String nombre2 = "";
    int cont2;
    int cont3;
    int cont4;
    int cont5;
    String registroTotal = "";
    String registroTotal2 = "";
    String registroTotal3 = "";
    String registroTotal4 = "";
    int conta2 = 0;
    int conta3 = 0;
    int conta4 = 0;
    int aux = 0;
    int valc1 = 0;
    int valc2 = 0;
    int valc3 = 0;
    int valc4 = 0;
}
